apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-9dvb34
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-9dvb34
  namespace: my-nginx-9dvb34
  labels:
    name: nginx-9dvb34
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-9dvb34
  template:
    metadata:
      namespace: my-nginx-9dvb34
      labels:
        name: nginx-9dvb34
    spec:
      containers:
      - name: nginx-9dvb34
        image: nginx
        ports:
        - containerPort: 80

